name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node 14
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'maven'

    - name: Build & Test
      run: npm run build
